#!/usr/bin/env bash
#list files

while IFS=: read -r username _ userid _ homedir _
do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homedir"
    echo
done < /etc/passwd
