#!/usr/bin/env bash
# This script displays a list of currently running processes, for all users, including those wthout a TTY, in a user-oriented format, and shows the process hierachy.
echo "List of currently running processes:"
ps -e -o user,pid,ppid,%cpu,%mem,start,time,command
echo
echo "Process hierachy:"
pstree -Ap
